name: app_environment
channels:
  - snowflake
dependencies:
  - streamlit
  - pandas
  - seaborn
  - networkx
  - numpy
  - altair
  - matplotlib
  - plotly
  - scikit-learn
  - scipy
  - gensim
  - lifelines=0.30.0
  - snowflake-snowpark-python
  - streamlit-echarts=0.4.0
  - streamlit-extras=0.4.0