name: app_environment
channels:
  - snowflake
dependencies:
  - altair=5.0.1
  - gensim=4.3.3
  - lifelines=0.30.0
  - matplotlib=3.10.0
  - networkx=3.4.2
  - numpy=1.26.4
  - pandas=2.2.3
  - plotly=5.24.1
  - python=3.10
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - snowflake-snowpark-python=
  - streamlit=1.49
  - streamlit-echarts=0.4.0
  - streamlit-extras=0.4.0